projects:
  - name: My project
    environments:
      - name: Production
        services:
          - name: credets-backend
            type: web
            runtime: docker
            plan: free
            region: singapore
            repo: https://github.com/nishatislam04/credets
            branch: main
            autoDeployTrigger: commit
            dockerfilePath: apps/backend/Containerfile
            dockerContext: .
            healthCheckPath: /healthz
            envVars:
              - key: POSTGRES_URL
                sync: false
              - key: DB_HOST
                sync: false
              - key: DB_PORT
                sync: false
              - key: DB_USER
                sync: false
              - key: DB_PASSWORD
                sync: false
              - key: DB_NAME
                sync: false
              - key: DB_TLS
                value: "true"
              - key: ENC_KEY
                sync: false
              - key: CSRF_SECRET_KEY
                sync: false
              - key: FRONTEND_APP
                value: https://credets.onrender.com
              - key: PORT
                value: "8000"
              - key: NODE_ENV
                value: production
              - key: STORAGE_ACCESS_KEY_ID
                sync: false
              - key: STORAGE_SECRET_ACCESS_KEY
                sync: false
              - key: STORAGE_ENDPOINT
                sync: false
              - key: STORAGE_PUBLIC_URL
                sync: false
              - key: STORAGE_REGION
                sync: false
              - key: STORAGE_BUCKET
                sync: false
